SCR_AvailableActionsDisplay {
 m_aActions +{
  SCR_AvailableActionContext "{69A8A34F00000010}" {
   m_aConditions {
    PFC_IsInPlaneCondition "{69A8A34F00000012}" {
    }
    SCR_CharacterIsInVehicleCondition "{69A8A34F00000011}" {
     m_bIsDriver 1
    }
   }
   m_sTag "PFC_THROTTLE_UP"
   m_sAction "Airplane_ThrottleUp"
   m_sName "Throttle up"
  }
  SCR_AvailableActionContext "{69A8A34F00000020}" {
   m_aConditions {
    PFC_IsInPlaneCondition "{69A8A34F00000022}" {
    }
    SCR_CharacterIsInVehicleCondition "{69A8A34F00000021}" {
     m_bIsDriver 1
    }
   }
   m_sTag "PFC_THROTTLE_DOWN"
   m_sAction "Airplane_ThrottleDown"
   m_sName "Throttle down"
  }
 }
}
