SCR_KeyBindingMenuConfig {
 m_KeyBindingCategories {
  SCR_KeyBindingCategory "{69A8A34E00000000}" {
   m_sName "PropFlightCore"
   m_sDisplayName "Propeller Flight Core"
   m_KeyBindingEntries {
    SCR_KeyBindingEntry "{69A8A34E00000001}" {
     m_sActionName "separator"
     m_sDisplayName "Flight Controls"
    }
    SCR_KeyBindingEntry "{69A8A34E00000002}" {
     m_sActionName "PFC_Pitch"
     m_sDisplayName "Pitch Up"
     m_sPreset "forward"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000003}" {
     m_sActionName "PFC_Pitch"
     m_sDisplayName "Pitch Down"
     m_sPreset "back"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000004}" {
     m_sActionName "PFC_Roll"
     m_sDisplayName "Roll Left"
     m_sPreset "left"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000005}" {
     m_sActionName "PFC_Roll"
     m_sDisplayName "Roll Right"
     m_sPreset "right"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000006}" {
     m_sActionName "PFC_Yaw"
     m_sDisplayName "Yaw Left"
     m_sPreset "left"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000007}" {
     m_sActionName "PFC_Yaw"
     m_sDisplayName "Yaw Right"
     m_sPreset "right"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000008}" {
     m_sActionName "PFC_ThrottleUp"
     m_sDisplayName "Throttle Up"
     m_sPreset "hold"
     m_ePrefixType CONTINUOUS
    }
    SCR_KeyBindingEntry "{69A8A34E00000009}" {
     m_sActionName "PFC_ThrottleDown"
     m_sDisplayName "Throttle Down"
     m_sPreset "hold"
     m_ePrefixType CONTINUOUS
    }
   }
  }
 }
}
